services:
  - type: web
    name: forgegameia-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: https://acygynvrlutuezjdhetd.supabase.co
        sync: false
      - key: sb_publishable_0Gps9Mbnx2pbcjYN5YIzjA_8749mEaa
        sync: false
